name: release-github

# on:
#   release:
#     types: [published]

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: "https://npm.pkg.github.com"
          scope: "@gerdu-tool"
          always-auth: true

      - name: Installing
        run: yarn install --frozen-lockfile

      - name: Testing
        run: yarn run test:coverage

      - name: Linting
        run: yarn run lint

      - name: Linting:Flow
        run: yarn run flow

      - name: export RELEASE_TAG
        run: export RELEASE_TAG=$(git tag --sort=committerdate)

      - name: set package version
        run: yarn version --force --no-git-tag-version --no-commit-hooks --new-version $RELEASE_TAG

      - name: install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: update package.json scope
        run: echo "`jq '.name="@gerdu-tool/cli"' package.json`" > package.json
      
      - name: update package.json version
        run: echo "`jq '.version="${RELEASE_TAG}"' package.json`" > package.json

      - name: Building
        run: yarn run build:prod

      - name: Authenticate with GitHub package registry
        run: yarn config set @gerdu-tool:registry https://npm.pkg.github.com

      # - name: Publishing
      #   run: yarn publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
